"""moderator -> moderator.

Revision ID: 67d7db37ad59
Revises: 8558573e5a68
Create Date: 2022-09-30 21:25:37.977186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d7db37ad59'
down_revision = '8558573e5a68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediators_id'), 'mediator', ['id'], unique=False)
    op.drop_index('ix_moderator_id', table_name='moderator')
    op.drop_table('moderator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderator_id', 'moderator', ['id'], unique=False)
    op.drop_index(op.f('ix_mediators_id'), table_name='mediators')
    op.drop_table('mediators')
    # ### end Alembic commands ###
