"""Add other usertables.

Revision ID: 8558573e5a68
Revises: 0cfb481f6fdd
Create Date: 2022-09-10 14:40:18.803579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8558573e5a68'
down_revision = '0cfb481f6fdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderator_id'), 'moderator', ['id'], unique=False)
    op.create_table('spectator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spectator_id'), 'spectator', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spectator_id'), table_name='spectator')
    op.drop_table('spectator')
    op.drop_index(op.f('ix_moderator_id'), table_name='moderator')
    op.drop_table('moderator')
    # ### end Alembic commands ###
