"""Clear All.

Revision ID: 960b75fab735
Revises: 989b75bd7327
Create Date: 2022-08-15 14:12:57.870046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960b75fab735'
down_revision = '989b75bd7327'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_userposts_id', table_name='userposts')
    op.drop_table('userposts')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_nickname', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=True),
    sa.Column('join_time', sa.DATETIME(), nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=128), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=256), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=2), nullable=True),
    sa.Column('birth', sa.DATE(), nullable=True),
    sa.Column('info', sa.TEXT(), nullable=True),
    sa.Column('is_spectator', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_nickname', 'users', ['nickname'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('userposts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_userposts_id', 'userposts', ['id'], unique=False)
    # ### end Alembic commands ###
