"""Add avatar.

Revision ID: e79dbd451111
Revises: 67d7db37ad59
Create Date: 2022-10-02 18:18:48.576285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79dbd451111'
down_revision = '67d7db37ad59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_id', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_id')
    # ### end Alembic commands ###
